services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_db:/data

volumes:
  postgres_db_data:
  redis_db:
    driver: local
